In [16]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 23 12:22:38 2023

@author: vishalr
"""
import numpy as np
import pandas as pd
import pickle

# change this to the folder where you store your data
data_dir = r"/content/sample_data/"

# each of the two data frames below have 20,000 rows, each corresponding to one sample from the original graph
# each sample consists of 21 nodes; node_labels contains the names of these 21 nodes of the form Vxyz
# each node is a DNA fragment of length 500 bases; so Vxyz coveres region [500*xyz, 500*xyz+500)
# adjacency_matrix has the flattended adjacecny matrix for each of these 20,000 samples
# so each row is of dimension 21*21 = 441

# node_labels = pd.read_pickle(data_dir+'df_chr2L_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot_sample_node_matrix')
# adjacency_matrix = pd.read_pickle(data_dir+'df_chr2L_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot')

node_labels_chr2L = np.load(data_dir + 'df_chr2L_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot_sample_node_matrix.npy')
adjacency_matrix_chr2L = np.load(data_dir + 'df_chr2L_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot.npy')

node_labels_chr2R = np.load(data_dir + 'df_chr2R_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot_sample_node_matrix.npy')
adjacency_matrix_chr2R = np.load(data_dir + 'df_chr2R_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot.npy')

node_labels_chr3L = np.load(data_dir + 'df_chr3L_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot_sample_node_matrix.npy')
adjacency_matrix_chr3L = np.load(data_dir + 'df_chr3L_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot.npy')

node_labels_chr3R = np.load(data_dir + 'df_chr3R_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot_sample_node_matrix.npy')
adjacency_matrix_chr3R = np.load(data_dir + 'df_chr3R_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot.npy')

# just seeing the size of input; doesn't really do anything
print("chr2L node labels shape:", node_labels_chr2L.shape)
print("chr2L adjacency matrix shape:", adjacency_matrix_chr2L.shape)
print("chr2R node labels shape:", node_labels_chr2R.shape)
print("chr2R adjacency matrix shape:", adjacency_matrix_chr2R.shape)
print("chr3L node labels shape:", node_labels_chr3L.shape)
print("chr3L adjacency matrix shape:", adjacency_matrix_chr3L.shape)
print("chr3R node labels shape:", node_labels_chr3R.shape)
print("chr3R adjacency matrix shape:", adjacency_matrix_chr3R.shape)


chr2L node labels shape: (20000, 21)
chr2L adjacency matrix shape: (20000, 442)
chr2R node labels shape: (20000, 21)
chr2R adjacency matrix shape: (20000, 442)
chr3L node labels shape: (20000, 21)
chr3L adjacency matrix shape: (20000, 442)
chr3R node labels shape: (20000, 21)
chr3R adjacency matrix shape: (20000, 442)


In [14]:
# We assume that PyTorch is already installed
import torch
torchversion = torch.__version__

# Install PyTorch Scatter, PyTorch Sparse, and PyTorch Geometric
!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-{torchversion}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-{torchversion}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

# Visualization
import networkx as nx
import matplotlib.pyplot as plt

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done


In [17]:
# trying print the shape of the loaded array to get the number of samples
print(f'Number of samples: {adjacency_matrix_chr2L.shape[0]}')

Number of samples: 20000


In [18]:
#part1a: delete repeated node in adjacency matrix
import numpy as np

def remove_duplicates(node_labels, adj_matrix):
    unique_nodes = []
    unique_indices = []

    for idx, node in enumerate(node_labels):
        if node not in unique_nodes:
            unique_nodes.append(node)
            unique_indices.append(idx)

    unique_nodes = np.array(unique_nodes)
    sample_adj_matrix = adj_matrix[np.ix_(unique_indices, unique_indices)]

    return unique_nodes, sample_adj_matrix

# test whether it is functioning
sample_node_labels = np.array([1, 2, 2, 3, 4, 4])
sample_adj_matrix = np.array([
    [0, 1, 1, 0, 0, 0],
    [1, 0, 1, 0, 0, 0],
    [1, 1, 0, 1, 0, 0],
    [0, 0, 1, 0, 1, 1],
    [0, 0, 0, 1, 0, 1],
    [0, 0, 0, 1, 1, 0]
])

cleaned_nodes, cleaned_adj_matrix = remove_duplicates(sample_node_labels, sample_adj_matrix)

print("Cleaned Nodes:", cleaned_nodes)
print("Cleaned Adjacency Matrix:\n", cleaned_adj_matrix)

Cleaned Nodes: [1 2 3 4]
Cleaned Adjacency Matrix:
 [[0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [19]:
import torch
from torch_geometric.data import Data, InMemoryDataset, DataLoader
from torch_geometric.utils import from_scipy_sparse_matrix
import scipy.sparse as sp
import numpy as np


def create_graph_data(adjacency_matrix, node_labels, label_number):
    graphs = []
    for i in range(adjacency_matrix.shape[0]):
        row = adjacency_matrix[i]
        labels = node_labels[i]
        assert len(row) == 21 * 21 + 1, f"Each row should have 21*21 + 1 elements, but got {len(row)} elements."
        row = row[:-1]  # remove -1 row
        assert len(row) == 21 * 21, f"Each row should have 21*21 elements after removing -1 column, but got {len(row)} elements."
        adj_matrix = row.reshape((21, 21))
        unique_nodes = []
        unique_indices = []
        for idx, node in enumerate(labels):
            if node not in unique_nodes:
                unique_nodes.append(node)
                unique_indices.append(idx)
        labels = np.array(unique_nodes)
        adj_matrix = adj_matrix[np.ix_(unique_indices, unique_indices)]
        edge_index, edge_attr = from_scipy_sparse_matrix(sp.coo_matrix(adj_matrix))
        x = torch.tensor(labels, dtype=torch.float).view(-1, 1)
        y = torch.tensor([label_number], dtype=torch.long)
        graph_data = Data(x=x, edge_index=edge_index, y=y)
        graphs.append(graph_data)
    return graphs

worklist_node_labels = [node_labels_chr2L, node_labels_chr2R, node_labels_chr3L, node_labels_chr3R]
worklist_adjacency_matrix = [adjacency_matrix_chr2L, adjacency_matrix_chr2R, adjacency_matrix_chr3L, adjacency_matrix_chr3R]

dataset = []
for label_number in range(len(worklist_adjacency_matrix)):
    adj_matrix = worklist_adjacency_matrix[label_number]
    node_labels = worklist_node_labels[label_number]
    graphs = create_graph_data(adj_matrix, node_labels, label_number)
    dataset.extend(graphs)

class MyDataset(InMemoryDataset):
    def __init__(self, data_list, transform=None, pre_transform=None):
        self.data_list = data_list
        super(MyDataset, self).__init__(None, transform, pre_transform)
        self.data, self.slices = self.collate(data_list)

    def len(self):
        return len(self.data_list)

    def get(self, idx):
        return self.data_list[idx]

my_dataset = MyDataset(dataset)

num_node_features = my_dataset[0].x.size(1)
num_classes = len(set([data.y.item() for data in my_dataset]))


# Calculate num_node_features and num_classes
num_node_features = my_dataset[0].x.size(1)
num_classes = len(set([data.y.item() for data in my_dataset]))

# Split the dataset into training, validation, and test sets
train_dataset = my_dataset[:int(len(my_dataset) * 0.8)]
val_dataset = my_dataset[int(len(my_dataset) * 0.8):int(len(my_dataset) * 0.9)]
test_dataset = my_dataset[int(len(my_dataset) * 0.9):]

print(f'Training set   = {len(train_dataset)} graphs')
print(f'Validation set = {len(val_dataset)} graphs')
print(f'Test set       = {len(test_dataset)} graphs')

# Create mini-batches
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

# Verify if everything works properly
print('\nTrain loader:')
for i, subgraph in enumerate(train_loader):
    print(f' - Subgraph {i}:')
    print(f'  Node labels (x): {subgraph.x}')
    print(f'  Labels (y): {subgraph.y}')
    break  # Print only the first batch

print('\nValidation loader:')
for i, subgraph in enumerate(val_loader):
    print(f' - Subgraph {i}:')
    print(f'  Node labels (x): {subgraph.x}')
    print(f'  Labels (y): {subgraph.y}')
    break  # Print only the first batch

print('\nTest loader:')
for i, subgraph in enumerate(test_loader):
    print(f' - Subgraph {i}:')
    print(f'  Node labels (x): {subgraph.x}')
    print(f'  Labels (y): {subgraph.y}')
    break  # Print only the first batch

    # Create the custom dataset
my_dataset = MyDataset(dataset)




Training set   = 64000 graphs
Validation set = 8000 graphs
Test set       = 8000 graphs

Train loader:
 - Subgraph 0:
  Node labels (x): tensor([[10498.],
        [41500.],
        [44436.],
        ...,
        [17150.],
        [13088.],
        [13229.]])
  Labels (y): tensor([0, 2, 1, 2, 2, 3, 0, 2, 1, 1, 1, 0, 2, 2, 2, 0, 1, 1, 0, 0, 3, 0, 1, 1,
        1, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2, 1, 0, 0, 1, 2, 2, 1, 1, 0, 0, 1, 0, 1,
        1, 3, 2, 0, 2, 0, 1, 2, 1, 1, 2, 0, 2, 2, 2, 1])

Validation loader:
 - Subgraph 0:
  Node labels (x): tensor([[24202.],
        [51201.],
        [29736.],
        ...,
        [25822.],
        [48308.],
        [ 9268.]])
  Labels (y): tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

Test loader:
 - Subgraph 0:
  Node labels (x): tensor([[51678.],
        [42148.],
        [19282.],
 

/usr/local/lib/python3.10/dist-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


In [20]:
#part 2a: to create a numpy array of all node labels, in file order
import numpy as np

# Create a 1D array of length 24000 to store all known node names
all_node_names = np.full(60000 * 4, -1, dtype=node_labels_chr2L.dtype)

# Function to fill node names
def fill_node_names_basic(all_node_names, node_labels, start_index, max_nodes=6000):
    unique_nodes = set()
    current_index = start_index

    for row in node_labels:
        for node in row:
            if node not in unique_nodes:
                unique_nodes.add(node)
                all_node_names[current_index] = node
                current_index += 1
                if current_index >= start_index + max_nodes:
                    return current_index

    # Fill remaining positions with -1 if less than max_nodes nodes are found
    while current_index < start_index + max_nodes:
        all_node_names[current_index] = -1
        current_index += 1

    return current_index

# Fill each section of the array
next_index = fill_node_names_basic(all_node_names, node_labels_chr2L, 0)
next_index = fill_node_names_basic(all_node_names, node_labels_chr2R, 1 * 60000 - 1)
next_index = fill_node_names_basic(all_node_names, node_labels_chr3L, 2 * 60000 - 1)
next_index = fill_node_names_basic(all_node_names, node_labels_chr3R, 3 * 60000 - 1)

# Print the result to check
print("All node names array:", all_node_names)
print("Shape of all node names array:", all_node_names.shape)

# Print each section to verify
print("Unique nodes in first section:")
print(all_node_names[:60000-1])

print("Unique nodes in second section:")
print(all_node_names[60000-1:120000-1])

print("Unique nodes in third section:")
print(all_node_names[120000-1:180000-1])

print("Unique nodes in fourth section:")
print(all_node_names[180000-1:])

All node names array: [ 5997 19835   969 ...    -1    -1    -1]
Shape of all node names array: (240000,)
Unique nodes in first section:
[ 5997 19835   969 ...    -1    -1    -1]
Unique nodes in second section:
[34307 23565  5042 ...    -1    -1    -1]
Unique nodes in third section:
[41331  1284  1255 ...    -1    -1    -1]
Unique nodes in fourth section:
[36929 11842 11826 ...    -1    -1    -1]


In [24]:
import torch
import torch.nn.functional as F
from torch.nn import Linear, Sequential, BatchNorm1d, ReLU, Dropout
from torch_geometric.nn import GCNConv, GINConv
from torch_geometric.nn import global_mean_pool, global_add_pool


# class GCN(torch.nn.Module):
#     """GCN"""
#     def __init__(self, dim_h):
#         super(GCN, self).__init__()
#         self.conv1 = GCNConv(dataset.num_node_features, dim_h)
#         self.conv2 = GCNConv(dim_h, dim_h)
#         self.conv3 = GCNConv(dim_h, dim_h)
#         self.lin = Linear(dim_h, dataset.num_classes)

#     def forward(self, x, edge_index, batch):
#         # Node embeddings
#         h = self.conv1(x, edge_index)
#         h = h.relu()
#         h = self.conv2(h, edge_index)
#         h = h.relu()
#         h = self.conv3(h, edge_index)

#         # Graph-level readout
#         hG = global_mean_pool(h, batch)

#         # Classifier
#         h = F.dropout(hG, p=0.5, training=self.training)
#         h = self.lin(h)

#         return hG, F.log_softmax(h, dim=1)

class GIN(torch.nn.Module):
    """GIN"""
    def __init__(self, dim_h):
        super(GIN, self).__init__()
        self.conv1 = GINConv(
            Sequential(Linear(my_dataset.num_node_features, dim_h),
                       BatchNorm1d(dim_h), ReLU(),
                       Linear(dim_h, dim_h), ReLU()))
        self.conv2 = GINConv(
            Sequential(Linear(dim_h, dim_h), BatchNorm1d(dim_h), ReLU(),
                       Linear(dim_h, dim_h), ReLU()))
        self.conv3 = GINConv(
            Sequential(Linear(dim_h, dim_h), BatchNorm1d(dim_h), ReLU(),
                       Linear(dim_h, dim_h), ReLU()))
        self.lin1 = Linear(dim_h*3, dim_h*3)
        self.lin2 = Linear(dim_h*3, my_dataset.num_classes)

    def forward(self, x, edge_index, batch):
        # Node embeddings
        h1 = self.conv1(x, edge_index)
        h2 = self.conv2(h1, edge_index)
        h3 = self.conv3(h2, edge_index)

        # Graph-level readout
        h1 = global_add_pool(h1, batch)
        h2 = global_add_pool(h2, batch)
        h3 = global_add_pool(h3, batch)

        # Concatenate graph embeddings
        h = torch.cat((h1, h2, h3), dim=1)

        # Classifier
        h = self.lin1(h)
        h = h.relu()
        h = F.dropout(h, p=0.5, training=self.training)
        h = self.lin2(h)

        return h, F.log_softmax(h, dim=1)

gin = GIN(dim_h=32)

In [26]:
def train(model, loader):
    criterion = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(),
                                      lr=0.01,
                                      weight_decay=0.01)
    epochs = 5

    model.train()
    for epoch in range(epochs+1):
        #print(epoch)
        total_loss = 0
        acc = 0
        val_loss = 0
        val_acc = 0

        # Train on batches
        for data in loader:
          optimizer.zero_grad()
          _, out = model(data.x, data.edge_index, data.batch)
          loss = criterion(out, data.y)
          total_loss += loss / len(loader)
          acc += accuracy(out.argmax(dim=1), data.y) / len(loader)
          loss.backward()
          optimizer.step()

          # Validation
          val_loss, val_acc = test(model, val_loader)

          # print per epoch to see if the accuracy goes up!
        print(f'Epoch {epoch:>0} | Train Loss: {total_loss:.2f} '
            f'| Train Acc: {acc*100:>5.2f}% '
            f'| Val Loss: {val_loss:.2f} '
            f'| Val Acc: {val_acc*100:.2f}%')


    test_loss, test_acc = test(model, test_loader)
    print(f'Test Loss: {test_loss:.2f} | Test Acc: {test_acc*100:.2f}%')

    return model

@torch.no_grad()
def test(model, loader):
    criterion = torch.nn.CrossEntropyLoss()
    model.eval()
    loss = 0
    acc = 0

    for data in loader:
        _, out = model(data.x, data.edge_index, data.batch)
        loss += criterion(out, data.y) / len(loader)
        acc += accuracy(out.argmax(dim=1), data.y) / len(loader)

    return loss, acc

def accuracy(pred_y, y):
    """Calculate accuracy."""
    return ((pred_y == y).sum() / len(y)).item()

gin = train(gin, train_loader)

Epoch 0 | Train Loss: 1.12 | Train Acc: 45.11% | Val Loss: 2.34 | Val Acc: 16.16%
Epoch 1 | Train Loss: 1.10 | Train Acc: 46.14% | Val Loss: 1.89 | Val Acc: 33.35%
Epoch 2 | Train Loss: 1.09 | Train Acc: 46.51% | Val Loss: 1.75 | Val Acc: 38.32%
Epoch 3 | Train Loss: 1.10 | Train Acc: 46.46% | Val Loss: 1.81 | Val Acc: 32.44%
Epoch 4 | Train Loss: 1.09 | Train Acc: 46.89% | Val Loss: 1.37 | Val Acc: 49.36%
Epoch 5 | Train Loss: 1.09 | Train Acc: 46.80% | Val Loss: 1.61 | Val Acc: 38.95%
Test Loss: 1.59 | Test Acc: 40.66%


In [2]:

label_mapping = {0: '2L', 1: '2R', 2: '3L', 3: '3R'}


import matplotlib.pyplot as plt
import networkx as nx
from torch_geometric.utils import to_networkx


fig, ax = plt.subplots(4, 4, figsize=(16, 16))
fig.suptitle('GIN - Graph classification')

for i, data in enumerate(dataset[1113-16:]):
    _, out = gin(data.x, data.edge_index, data.batch)
    predicted_class = out.argmax(dim=1).item()
    actual_class = data.y.item()
    color = "green" if predicted_class == actual_class else "red"

    ix = np.unravel_index(i, ax.shape)
    ax[ix].axis('off')
    G = to_networkx(dataset[1113-16+i], to_undirected=True)
    nx.draw_networkx(G,
                     pos=nx.spring_layout(G, seed=0),
                     with_labels=False,
                     node_size=150,
                     node_color=color,
                     width=0.8,
                     ax=ax[ix])

    classification_text = f"Predicted: {label_mapping[predicted_class]}, Actual: {label_mapping[actual_class]}"
    ax[ix].text(0.5, 0.9, classification_text, horizontalalignment='center', verticalalignment='center', transform=ax[ix].transAxes, color='black')

plt.show()


ModuleNotFoundError: No module named 'torch_geometric'