<a href="https://colab.research.google.com/github/everythingapplejj/Research-Graph-Embeddings-/blob/JJ/helperfunction_task_2ABCDE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Welcome to helper funcition task 2!

In [2]:
# testing out task 2a

In [3]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#testing visualization
#Implementation by Jiwoong Jung
import torch

#placeholder values:

# Print information about the dataset


# Visualization
import networkx as nx
import matplotlib.pyplot as plt
plt.rcParams['figure.dpi'] = 300
plt.rcParams.update({'font.size': 24})
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
"""
Created on Wed Aug 23 12:22:38 2023

@author: vishalr
"""

# we can use the node labels for the first set of the x values
# figure out ways to include diff files for the y_features (1st priority)
# for now, do the y label first,
# later consider the edge features and node features

import pandas as pd
import pickle
import numpy as np


#change this to the folder where you store your data
data_dir = ""

#each of the two data frames below have 20,000 rows, each corresponding to one sample from the original graph
#each sample consists of 21 nodes; node_labels contains the names of these 21 nodes of the form Vxyz
#each node is a DNA fragment of length 500 bases; so Vxyz coveres region [500*xyz, 500*xyz+500)
#adjacency_matrix has the flattended adjacecny matrix for each of these 20,000 samples
#so each row is of dimension 21*21 = 441


#node_labels = np.load(data_dir+'df_chr2R_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot_sample_node_matrix.npy')

#adjacency_matrix = np.load(data_dir+'df_chr2R_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot.npy')

worklist_node_labels = []
worklist_adjacency_matrix = []

#importing the rest of the files
# 2L = 0; 2R = 1; 3L = 2, 3R = 3

node_labels_2L = np.load(data_dir+'df_chr2L_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot_sample_node_matrix.npy')
adjacency_matrix_2L = np.load(data_dir+'df_chr2L_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot.npy')

worklist_node_labels.append(node_labels_2L)
worklist_adjacency_matrix.append(adjacency_matrix_2L)

node_labels_2R = np.load(data_dir+'df_chr2R_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot_sample_node_matrix.npy')
adjacency_matrix_2R = np.load(data_dir+'df_chr2R_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot.npy')

worklist_node_labels.append(node_labels_2R)
worklist_adjacency_matrix.append(adjacency_matrix_2R)

node_labels_3L = np.load(data_dir+'df_chr3L_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot_sample_node_matrix.npy')
adjacency_matrix_3L = np.load(data_dir+'df_chr3L_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot.npy')

worklist_node_labels.append(node_labels_3L)
worklist_adjacency_matrix.append(adjacency_matrix_3L)

node_labels_3R = np.load(data_dir+'df_chr3R_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot_sample_node_matrix.npy')
adjacency_matrix_3R = np.load(data_dir+'df_chr3R_drosophila_ChIA_Drop_0.1_PASS_20000_MCMC_pivot.npy')


worklist_node_labels.append(node_labels_3R)
worklist_adjacency_matrix.append(adjacency_matrix_3R)

In [4]:
for i in range(0,len(worklist_adjacency_matrix)):
  worklist_adjacency_matrix[i] = worklist_adjacency_matrix[i][:,:-1]

In [5]:
print(worklist_node_labels)
print(len(worklist_node_labels))
print(worklist_adjacency_matrix)

[array([[ 5997, 19835,   969, ...,  4455, 27017, 27025],
       [41207, 22040, 41207, ...,   135,   186,   153],
       [13615, 16412, 16377, ..., 41754, 41780, 41767],
       ...,
       [39599,  9995, 38842, ..., 33868, 20856, 14348],
       [39954,  9995, 10131, ...,  2117,  2259,  2251],
       [32509, 19793, 19783, ...,  7313, 42107, 41499]]), array([[34307, 23565,  5042, ...,  5114, 12844, 12993],
       [36450, 36179, 36450, ..., 22359, 28058, 30979],
       [36450, 36179, 33947, ...,  9673, 20209, 12537],
       ...,
       [ 7427, 39513, 19626, ..., 25109, 25119, 27062],
       [33656, 20125, 24230, ..., 28043, 29127, 29091],
       [ 8127, 38554,  7700, ..., 24445, 25489,  3057]]), array([[41331,  1284,  1255, ..., 32082, 18737, 18660],
       [ 1284,  1349,  1363, ...,  3939,  5692, 17395],
       [24386,  5147, 32020, ..., 28096,  6446, 41308],
       ...,
       [ 3375, 19321,  1419, ..., 17371, 28421, 17371],
       [44210,  1306,  3592, ..., 11490,  1774, 35930],
       

Task 2A: Unique length 60,000:  [0,60,000 - 1] for each chromosome arm

In [6]:
import numpy as np
node_labels_addr = np.array([], dtype = int)
chromosome_arm_count = 4
for i in range(0, 60000 * chromosome_arm_count):
  node_labels_addr = np.append(node_labels_addr,[i]) # this is amended to take 240,000 unique numbers

#print(node_labels_addr)
#print(node_labels_addr.shape)
print(np.min(node_labels_addr))
print(np.max(node_labels_addr))
init = node_labels_addr.shape[0]
node_labels_addr = node_labels_addr.reshape((init,1))
print(node_labels_addr.shape)
print(node_labels_addr)

0
239999
(240000, 1)
[[     0]
 [     1]
 [     2]
 ...
 [239997]
 [239998]
 [239999]]


We will go through the data cleaning process first



In [7]:
# Data cleaning function per subgraph
import numpy as np
def remove_duplicates(node_labels, adj_matrix):
  sample_nodes = node_labels
  sample_adj_matrix = adj_matrix
  i = 0
  j = i + 1
  while(i < len(sample_nodes) - 1):
    if(sample_nodes[i] == sample_nodes[j]):
      sample_nodes = np.delete(sample_nodes,j)
      sample_adj_matrix = np.delete(np.delete(sample_adj_matrix, j, 0), j, 1)
      if(j >= len(sample_nodes)):
        i = i + 1
        j = i + 1
      continue
    else:
      j = j + 1
      if(j >= len(sample_nodes)):
        i = i + 1
        j = i + 1
  return sample_nodes, sample_adj_matrix

In [8]:
# algorithm for subgraph delete duplicate
worklist_new_adj_matrix = []
worklist_new_node_labels = []

counter = 0
label_number = 0

for adjacency_matrix in worklist_adjacency_matrix:
  sample_graphs = ""
  sample_nodes = ""
  adj_matrix = []
  node_labels = []
  for graph in adjacency_matrix:
    sample_graph = graph.reshape(21,21)
    sample_node = worklist_node_labels[label_number][counter]
    sample_node, sample_graphs = remove_duplicates(sample_node, sample_graph)
    adj_matrix.append(sample_graphs)
    node_labels.append(sample_node)
    counter = counter + 1
  worklist_new_adj_matrix.append(adj_matrix)
  worklist_new_node_labels.append(node_labels)
  counter = 0
  label_number = label_number + 1

In [9]:
print(len(worklist_new_adj_matrix))

4


In [10]:
# testing which method is faster:
import numpy as np
import time

# Using np.vstack in a loop
start_time = time.time()
a = np.empty((0, 2), dtype=int)
for i in range(200000):
    new_row = np.array([i, i+1])
    a = np.vstack([a, new_row])
print("Time with vstack: {:.2f} seconds".format(time.time() - start_time))

# Using list and converting to np.array at the end
start_time = time.time()
a_list = []
for i in range(200000):
    new_row = [i, i+1]
    a_list.append(new_row)
a = np.array(a_list, dtype=int)
print("Time with list: {:.2f} seconds".format(time.time() - start_time))


#utilizing list is faster! vstack has exponential growth in time.

Time with vstack: 37.02 seconds
Time with list: 0.40 seconds


Task 2B : Same shape as 2A, but includes the node features. We currently do not have datas on node features, we do have datas on node labels. We will discuss about this in our next meeting.

In [11]:
task_2b_list = np.zeros_like(node_labels_addr)
task_2b = np.array(task_2b_list, dtype=int)
print("Result of Task 2B: ")
print(task_2b)
print("Shape of task 2B: ")
print(task_2b.shape)

# Each of the subarrays will carry important information on the node

Result of Task 2B: 
[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
Shape of task 2B: 
(240000, 1)


Task 2C : Pairs of nodes connected by an edge


Task 2D : Same shape as Task 2C, 80,000 unique numbers form all 4 chromosomes, indicating which subgraphs it came from.


Task 2E : Same shape as Task 2E, 4 unique numbers from all 4 chromosomes, indicating which chromosome arm it came from.

In [13]:
#using list instead of vstack

import numpy as np


task_2c_list = []
task_2d_list = []
task_2e_list = []

# for task 2c, you need to reflect the 2A node labels

counter_2d = 0
counter_out = 0
for chromosome in worklist_new_adj_matrix:
    lookup = worklist_new_node_labels[counter_out]
    counter_in = 0
    for graphs in chromosome:
        lookup_vid = lookup[counter_in]
        show = np.where(graphs == 1)
        for i in range(len(show[0])):
            offset = counter_out * 60000
            task_2c_list.append([offset + lookup_vid[show[0][i]], offset + lookup_vid[show[1][i]]]) # now reflecting 2A Vids
            task_2d_list.append([counter_2d])
            task_2e_list.append([counter_out])
        counter_in += 1
        counter_2d += 1
    counter_out += 1
    print(counter_out)


task_2c = np.array(task_2c_list, dtype=int)
task_2d = np.array(task_2d_list, dtype=int)
task_2e = np.array(task_2e_list, dtype=int)

print("Result of Task 2C: ")
print(task_2c)
print("Shape of task 2C: ")
print(task_2c.shape)
print("Result of Task 2D: ")
print(task_2d)
print("Shape of task 2D: ")
print(task_2d.shape)
print("Result of Task 2E: ")
print(task_2e)
print("Shape of task 2E: ")
print(task_2e.shape)


1
2
3
4
Result of Task 2C: 
[[  5997  19835]
 [  5997    969]
 [ 19835   5997]
 ...
 [199026 198944]
 [199026 198990]
 [199026 199015]]
Shape of task 2C: 
(2996406, 2)
Result of Task 2D: 
[[    0]
 [    0]
 [    0]
 ...
 [79999]
 [79999]
 [79999]]
Shape of task 2D: 
(2996406, 1)
Result of Task 2E: 
[[0]
 [0]
 [0]
 ...
 [3]
 [3]
 [3]]
Shape of task 2E: 
(2996406, 1)


In [15]:
#sample output:
print("Random Edge (pairs of node): ", task_2c[1996410])
print("Which subgraph is it from (Unique Numbers): ", task_2d[1996410])
print("Which chromosome is it from: ", task_2e[1996410])


print("Random Edge (pairs of node): ", task_2c[0])
print("Which subgraph is it from (Unique Numbers): ", task_2d[0])
print("Which chromosome is it from: ", task_2e[0])


print("Random Edge (pairs of node): ", task_2c[len(task_2c) - 1])
print("Which subgraph is it from (Unique Numbers): ", task_2d[len(task_2c) - 1])
print("Which chromosome is it from: ", task_2e[len(task_2c) - 1])

Random Edge (pairs of node):  [146810 137086]
Which subgraph is it from (Unique Numbers):  [53391]
Which chromosome is it from:  [2]
Random Edge (pairs of node):  [ 5997 19835]
Which subgraph is it from (Unique Numbers):  [0]
Which chromosome is it from:  [0]
Random Edge (pairs of node):  [199026 199015]
Which subgraph is it from (Unique Numbers):  [79999]
Which chromosome is it from:  [3]


Once the Tasks are completed, we will copy the information to the files.